version: '3.4'

services:
  signalr_web:
    image: ${DOCKER_REGISTRY-}signalrweb
    build:
      context: .
      dockerfile: SignalR_Web/Dockerfile

  signalr_api:
    image: ${DOCKER_REGISTRY-}signalrapi
    build:
      context: .
      dockerfile: SignalR_API/Dockerfile

